#!/bin/bash

# For the release-staging branch his script bumps the Tensile version and hash

OLD_TENSILE_VERSION="TENSILE_VERSION 4.42.0"
NEW_TENSILE_VERSION="TENSILE_VERSION 4.43.0"

OLD_TENSILE_HASH="1e25e645f7f60c8edbe55ff1cf789e0daf2468e6"
NEW_TENSILE_HASH="3acb803f67c18a767a31bab7e476e2a065c8c66a"

OLD_HIPBLASLT_VERSION="HIPBLASLT_VERSION 0.10"
NEW_HIPBLASLT_VERSION="HIPBLASLT_VERSION 0.12"

sed -i "s/${OLD_TENSILE_VERSION}/${NEW_TENSILE_VERSION}/g" CMakeLists.txt

sed -i "s/${OLD_TENSILE_HASH}/${NEW_TENSILE_HASH}/g" tensile_tag.txt

sed -i "s/${OLD_HIPBLASLT_VERSION}/${NEW_HIPBLASLT_VERSION}/g" CMakeLists.txt
